### ISSUE TITLE
How to access dropdown in PhoneInput component

### ISSUE THREAD

**Issue by enes-get-local** [uber/baseweb#3828] opened 2020-10-15 14:14 UTC
How to access dropdown events in PhoneInput component ? For example I want to prevent dropdown opening in automatic form filling.
![image](https://user-images.githubusercontent.com/70728456/96141567-d05fe580-0f09-11eb-86e9-23bbc8045639.png)

i can not see any way of access this dropdown

**Comment by sandgraham** [comment] 2020-10-15 17:29
Can you share a reproduction of this behavior using StackBlitz? You can fork [this sandbox](https://stackblitz.com/edit/react-xtufax?file=src/example.js).

**Comment by enes-get-local** [comment] 2020-10-16 09:31
> Can you share a reproduction of this behavior using StackBlitz? You can fork [this sandbox](https://stackblitz.com/edit/react-xtufax?file=src/example.js).

https://stackblitz.com/edit/react-xtufax-jbel29?file=src/example.js

**Comment by enes-get-local** [comment] 2020-10-16 13:03
https://app.slack.com/client/TCGFTAJMS/CCGJPJA1H/thread/CCGJPJA1H-1602770813.051700

There is thrad that we discuss

**Comment by sandgraham** [comment] 2020-10-30 20:09
Closing as this seems to be more directly addressed in #3846

**Closed by sandgraham** 2020-10-30 20:09 UTC
