### ISSUE TITLE
Country change in PhoneInput logs a " Cannot update during an existing state transition (such as within `render`)..." React error

### ISSUE THREAD

**Issue by julianruizsa** [uber/baseweb#3042] opened 2020-03-14 17:16 UTC
When selecting a country from the dropdown of a PhoneInput component, React throws an error (although the message is referenced as a warning) that says: "index.js:1 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state"

Not sure if related, but the sandbox example with the error log is laggy compared to the current docs example.

https://codesandbox.io/s/70h29?module=/example.js
## Current Behavior
Logs the error

## Expected Behavior
Should't log any error.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.64.1  |
| React   | 16.13.0        |
| browser |  Chrome 80.0.3987.132       |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment] 2020-03-14 17:21
Duplicate of #2980 and I believe a PR is merged that solves this (unreleased at this time though).

**Comment by houmark** [comment] 2020-03-14 17:22
#3038 should fix this and is merged.

**Comment by chasestarr** [comment] 2020-03-16 17:04
Closing as duplicate

**Closed by chasestarr** 2020-03-16 17:04 UTC
