### ISSUE TITLE
[DataTable] Component crashes on row selection when row array contains a number in first index

### ISSUE THREAD

**Issue by jasonbarone** [uber/baseweb#3073] opened 2020-03-18 23:45 UTC
## Current Behavior
When your data source has a number in the array's first index position, it will error on selection.

Example here: https://codesandbox.io/s/batch-actions-zutt8

To reproduce:
- Open example
- Click on a selection, or the select all button

## Expected Behavior
Component should not error.

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment] 2020-03-19 16:35
Can you please share more detailed reproduction steps? If I sort the `production budget` column I do not see an error

**Comment by jasonbarone** [comment] 2020-03-19 17:13
> Can you please share more detailed reproduction steps? If I sort the `production budget` column I do not see an error

Sorry I meant to say on selection, not on sort. I'll update issue.

**Comment by chasestarr** [comment] 2020-03-19 17:34
Thank you - I can reproduce

**Comment by chasestarr** [comment] 2020-03-20 22:56
Have you seen this problem not in codesandbox? I have not been able to reproduce anywhere else

**Comment by chasestarr** [comment] 2020-08-07 17:15
I'm going to close this issue since the error only comes up in codesandbox. Let me know if we can get a full app to similarly throw

**Closed by chasestarr** 2020-08-07 17:15 UTC
Labels: bug
