### ISSUE TITLE
How to hightlight when focus input after style applied? 

### ISSUE THREAD

**Issue by png-prakash** [uber/baseweb#4313] opened 2021-06-09 06:19 UTC
Hi,

Not able to highlight after I update input. How to fix this issue? I have to update style for on focus, if yes how to do?
Thanks

This is my code
```
<Input
  overrides={{
    Root: {
      style: () => ({
        borderTopWidth: "1px",
        borderTopStyle: 'solid',
        borderTopColor: '#B0B0B0',
        borderBottomWidth: "1px",
        borderBottomStyle: 'solid',
        borderBottomColor: '#B0B0B0',
        borderLeftWidth: "1px",
        borderLeftStyle: 'solid',
        borderLeftColor: '#B0B0B0',
        borderRightWidth: "1px",
        borderRightStyle: 'solid',
        borderRightColor: '#B0B0B0',
        borderTopLeftRadius: '4px',
        borderTopRightRadius: '4px',
        borderBottomLeftRadius: '4px',
        borderBottomRightRadius: '4px',
      }),
    },
    Input: {
      style: () => ({
        backgroundColor: "#FFFFFF",
      })
    }
  }}
  size={SIZE.large}  />
```

https://codesandbox.io/s/base-web-input-w408e

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.116.0  |
| React   |   16.13.1      |
| browser |    Chrome, Firefox     |

**Comment by williamernest** [comment] 2021-06-09 16:18
Can you provide a repro of this using sandbox? The easier it is for us to replicate your issue the faster we can assist.

**Comment by png-prakash** [comment] 2021-06-10 04:13
> Can you provide a repro of this using sandbox? The easier it is for us to replicate your issue the faster we can assist.

https://codesandbox.io/s/base-web-input-w408e

**Comment by akshatnitd** [comment] 2021-06-10 04:40
Hey @png-prakash 

Please try to use the following. 

```
         <Input
          placeholder="After updated style not showing highlight"
          overrides={{
            Root: {
              style: ({$isFocused}) => {
                const borderColor = $isFocused ? 'black': '#B0B0B0';
                return {
                  fontFamily: "aktiv-grotesk, sans-serif",
                  borderTopWidth: "1px",
                  borderTopStyle: "solid",
                  borderTopColor: borderColor,
                  borderBottomWidth: "1px",
                  borderBottomStyle: "solid",
                  borderBottomColor: borderColor,
                  borderLeftWidth: "1px",
                  borderLeftStyle: "solid",
                  borderLeftColor: borderColor,
                  borderRightWidth: "1px",
                  borderRightStyle: "solid",
                  borderRightColor: borderColor,
                  borderTopLeftRadius: "4px",
                  borderTopRightRadius: "4px",
                  borderBottomLeftRadius: "4px",
                  borderBottomRightRadius: "4px"
                };
              }
            },
            Input: {
              style: () => ({
                backgroundColor: "#FFFFFF"
              })
            }
          }}
          size={InputSize.large}
        />
```

**Comment by png-prakash** [comment] 2021-06-10 05:45
> Hey @png-prakash
> 
> Please try to use the following.
> 
> ```
>          <Input
>           placeholder="After updated style not showing highlight"
>           overrides={{
>             Root: {
>               style: ({$isFocused}) => {
>                 const borderColor = $isFocused ? 'black': '#B0B0B0';
>                 return {
>                   fontFamily: "aktiv-grotesk, sans-serif",
>                   borderTopWidth: "1px",
>                   borderTopStyle: "solid",
>                   borderTopColor: borderColor,
>                   borderBottomWidth: "1px",
>                   borderBottomStyle: "solid",
>                   borderBottomColor: borderColor,
>                   borderLeftWidth: "1px",
>                   borderLeftStyle: "solid",
>                   borderLeftColor: borderColor,
>                   borderRightWidth: "1px",
>                   borderRightStyle: "solid",
>                   borderRightColor: borderColor,
>                   borderTopLeftRadius: "4px",
>                   borderTopRightRadius: "4px",
>                   borderBottomLeftRadius: "4px",
>                   borderBottomRightRadius: "4px"
>                 };
>               }
>             },
>             Input: {
>               style: () => ({
>                 backgroundColor: "#FFFFFF"
>               })
>             }
>           }}
>           size={InputSize.large}
>         />
> ```

Hi @akshatnitd

Thanks for your answer. Its working fine for 1px border, Tittle shake when apply 2px border. Is it possible I can avoid?

https://codesandbox.io/s/base-web-input-forked-e1upo

**Comment by williamernest** [comment] 2021-06-10 17:53
You'll need to adjust the height/width of the nested elements if you change the border width to prevent the placeholder jump. Closing this issue as it's not a bug/feature.

**Closed by williamernest** 2021-06-10 17:53 UTC
