### ISSUE TITLE
[Select] got a weird behavior while using "Zhuyin"

### ISSUE THREAD

**Issue by huaying** [uber/baseweb#2215] opened 2019-11-01 17:19 UTC
Thanks you guys for creating the amazing library!
Here I want to explain a strange behavior happening while I was typing zhuyin with Select component.
 
[Zhuyin](https://en.wikipedia.org/wiki/Bopomofo) is a major input method for Taiwanese.
When you use zhuyin to type Chinese, It first shows a predicted word and you get a chance to correct it if the word is not what you want. You eventually press "enter" to finalize what you typed.

## Current Behavior
![Screen Recording 2019-11-02 at 12 55 44 AM](https://user-images.githubusercontent.com/3991678/68041869-7ff97300-fd0c-11e9-820b-0d5ecb0306b8.gif)

## Expected Behavior
I recorded this from [react-select](https://react-select.com/creatable). It seems to work correctly.
![Screen Recording 2019-11-02 at 12 57 38 AM](https://user-images.githubusercontent.com/3991678/68041896-930c4300-fd0c-11e9-8d4a-aa69d1775410.gif)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.13.0  |
| React   |         |
| browser |   chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment] 2019-11-01 18:33
@huaying thanks for opening the issue - would the expected behavior be that the input is cleared? once the option is created?

**Comment by huaying** [comment] 2019-11-02 10:31
Yeah the extra input "中文" should be cleared, thanks!

**Comment by gergelyke** [comment] 2019-11-04 18:18
@huaying - I couldn't reproduce the issue - can you help me what am I missing?

![ezgif-6-cb35404e4038](https://user-images.githubusercontent.com/2174968/68146218-5c8d1e80-feec-11e9-9463-180c1faa0894.gif)

**Comment by gergelyke** [comment] 2019-11-05 20:55
closing for now - please reopen if you can still reproduce the issue

**Closed by gergelyke** 2019-11-05 20:55 UTC
Labels: question

**Comment by huaying** [comment] 2019-11-06 07:51
Hi, thanks for trying Zhuyin :).  
ㄕㄨㄟ (mapping to 'f' 'j' 'o' respectively) can not actually consist of a character. You have to do something like ㄕㄨㄟˇ ('f' 'j' 'o' '3') and press enter to form a character "水" (it means water by the way).

**Comment by huaying** [comment] 2019-11-09 08:24
Hi @gergelyke,  The [PR](https://github.com/uber/baseweb/pull/2284) above is to solve this issue. Please take a look, thanks.

The basic idea is that we don't want to take into account  the Enter key events from Zhuyin.
