### ISSUE TITLE
Popover memory leak

### ISSUE THREAD

**Issue by zsobral** [uber/baseweb#2685] opened 2020-01-23 14:50 UTC
https://codesandbox.io/s/statefulpopover-gpkjx

## Current Behavior

the browser freeze after some clicks. I need to open chrome task manager and end the process. When checking the task manager the memory usage keeps increasing

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.43.0 |
| React   | 16.12.0 |
| browser | chrome |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment] 2020-01-23 21:18
I suspect, this is an issue with codesandbox, as I couldn't reproduce here: https://baseweb.design/components/popover/

Closing for now, but please let us know if you can repro outside of codesandboc

**Comment by zsobral** [comment] 2020-01-23 21:21
sorry, forgot to tell that is caused when using `triggerType="hover"`

**Comment by zsobral** [comment] 2020-01-23 21:26
sorry, forgot to tell that is caused when using a StatefulPopover with content StatefulMenu and the  triggerType is hover

**Comment by gergelyke** [comment] 2020-01-23 21:28
@zsobral could you reproduce the issue outside of codesandbox too?

**Comment by zsobral** [comment] 2020-01-23 21:30
Yes, I'm using with create-react-app and chrome

Em qui, 23 de jan de 2020 18:28, Gergely Nemeth <notifications@github.com>
escreveu:

**Comment by gergelyke** [comment] 2020-01-23 21:43
thank you

**Closed** 2020-02-06 03:02 UTC
Labels: bug
