### ISSUE TITLE
[Select] Console warning when selecting

### ISSUE THREAD

**Issue by jasonbarone** [uber/baseweb#3009] opened 2020-03-10 00:07 UTC
When using one of the basic examples for the Select, it's returning a console error:

```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

Example: https://codesandbox.io/s/select-basic-usage-czxlh

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.62.0  |
| React   |  16.8.6  |
| browser | Chrome latest  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment] 2020-03-10 00:12
Duplicate of #2980

**Closed** 2020-03-10 00:15 UTC
