### ISSUE TITLE
[Select] allow `inputValue` state to be controlled from outside component

### ISSUE THREAD

**Issue by chasestarr** [uber/baseweb#2982] opened 2020-03-05 00:32 UTC
Use case: I have some application event to clear the input value. Right now this is not possible. It should be optionally controlled through a prop

**Comment by candycanetrain** [comment] 2020-03-05 00:46
As stated offline, this is needed especially for Search as it is necessary to clear the `inputValue`. Currently, only `value` (which is the selectedValue as opposed to `inputValue`) is exposed right now. Pressing esc clears the `inputValue`, but I want to be able to clear it in other ways.

**Comment by chasestarr** [comment] 2020-03-06 21:33
@candycanetrain Can you provide more detail about what 'triggers' `inputValue` change in your use-case? Under what circumstances do we want the value to change?

**Comment by candycanetrain** [comment] 2020-03-09 18:44
> @candycanetrain Can you provide more detail about what 'triggers' `inputValue` change in your use-case? Under what circumstances do we want the value to change?

I was going to suggest allowing the [`clearValue()` function](https://github.com/uber/baseweb/blob/0aa015291d95428e2fefab03620d6ff66ca27773/src/select/select-component.js#L559) to be applicable for `inputValue`, but I see that it is already the case. The problem is that `renderClear()`, which renders the Clear button, has [a condition that only renders the Clear button if the `value` (selectedValue not inputValue) is present](https://github.com/uber/baseweb/blob/0aa015291d95428e2fefab03620d6ff66ca27773/src/select/select-component.js#L714-L716). This logic makes sense for when `type=Select` but not when `type=Search`.

For when `type=Search`, users should be able to see and click on the `Clear` button to set `inputValue` to an empty string. This can be fixed by allowing `renderClear` to render the `Clear` button for when `inputValue` is not empty.

![image](https://user-images.githubusercontent.com/19182744/76246557-2bef2580-61fb-11ea-928e-3815d4bc023c.png)

**Comment by chasestarr** [comment] 2020-03-09 20:33
Thank you for the description. Based on your requirements, I'm assuming the linked PR does not do what you need. The better fix would be to expand the cases where the clear button is rendered?

**Comment by chasestarr** [comment] 2020-03-09 22:57
@candycanetrain do you mind reviewing the latest diff here? https://baseweb-git-select-render-clear-button-if-input-value-exists.uber-ui-platform.now.sh/components/select/

**Comment by candycanetrain** [comment] 2020-03-09 23:16
@chasestarr i just reviewed the latest diff. It looks good, except when you've typed something in the input box and then click elsewhere triggering `onBlur`, the input box shows empty but the `Close` button is there. When you click on it again, the inputValue is present again. 

I'd suggest if `onBlurResetsInput` is set to false, the inputValue should show even when `onBlur` and not just when `inFocus`. Hope that makes sense.

Screenshots:

I type something in the box:
![image](https://user-images.githubusercontent.com/19182744/76265231-31f7fd00-6221-11ea-93d6-a3d4bf5af906.png)

I `blur` it, but `inputValue` is not empty (this part should be fixed):
![image](https://user-images.githubusercontent.com/19182744/76265263-476d2700-6221-11ea-8d27-2008731c11db.png)

I click again:
![image](https://user-images.githubusercontent.com/19182744/76265277-4f2ccb80-6221-11ea-9664-c06e6f052fe9.png)

**Comment by chasestarr** [comment] 2020-03-10 15:41
Yes - that makes sense. Thank You

**Comment by chasestarr** [comment] 2020-03-11 23:15
@candycanetrain pushed some changes that addresses your most recent comment. Please review when you have the opportunity

**Closed** 2020-03-12 20:35 UTC
Labels: feature
