### ISSUE TITLE
ToasterContainer breaks Next.js SSR

### ISSUE THREAD

**Issue by jgillich** [uber/baseweb#3430] opened 2020-06-22 17:23 UTC
ToasterContainer breaks server side rendering with Next.js, causing it to show a white page that will only render with JavaScript enabled.

The way Next.js handles this is very poor, there is no error message whatsoever and you basically just notice one day that SSR doesn't work. So I might also report this in Next.js, but there's probably something that can be done in baseweb as well.

I haven't been able to figure out what the issue is, ~~but importing `ToasterContainer` alone is enough to trigger it, you don't even have to use it~~ (edit: actually not true, happens only when you use it).

Here's how to reproduce it:

1. `git clone https://github.com/jgillich/nextjs-baseweb`
2. `yarn install && yarn run dev`
3. Go to `localhost:3000`
4. Click on the button and observe that everything is working
5. Turn off JavaScript via devtools
6. Reload the page and observe that it is completely empty
7. Optional: remove ToasterContainer, reload and observe that is working again

## Your Environment

Latest everything (see package.json in the example)

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by jgillich** [comment] 2020-06-22 17:38
I falsely assumed this was triggered by importing alone. So this works as a workaround:

```js
import {ToasterContainer as BaseToasterContainer} from 'baseui/toast'

const ToasterContainer = process.browser ? BaseToasterContainer : Fragment
```

So this is probably caused by the [toasterRef](https://github.com/uber/baseweb/blob/master/src/toast/toaster.js#L47) variable, which makes #3414 a related issue. Using context could be a solution here.

@grrowl can you confirm this issue?

**Comment by chasestarr** [comment] 2020-06-22 18:06
Thank you for the report @jgillich. We use nextjs for our docs site, and the [toast page](https://baseweb.design/components/toast) seems to work fine. Can you please review the [source code](https://github.com/uber/baseweb/tree/master/documentation-site) and maybe identify the difference in setup?

**Comment by jgillich** [comment] 2020-06-22 18:32
Sure. It looks like only elements inside `ToasterContainer` are swallowed by it, the rest continues to render fine. Interestingly, the [runnable examples don't wrap the Toast elements inside ToasterContainer](https://github.com/uber/baseweb/blob/master/documentation-site/examples/toast/basic.js#L23), so I'm not sure if this even a requirement. But the main example at the top does it that way.

With SSR and Toaster elements not wrapped inside ToasterContainer, we get what we have in the docs:

![image](https://user-images.githubusercontent.com/347965/85322397-93896200-b4c6-11ea-89c3-4471db6df692.png)

If you at the source there are still some parts there, so this is different from ToastContainer swallowing all children.

**Comment by jgillich** [comment] 2020-06-22 18:34
You can get the same by changing my example to:

```js
  return (
    <div>
      <Button onClick={() => toaster.positive('ok', {})}>Hello</Button>
      <p className={css({color: theme.colors.accent600})}>Styled by hook</p>
      <ToasterContainer />
      <Toast>Default info notification</Toast>
      <Toast kind={KIND.positive}>Positive notification</Toast>
      <Toast kind={KIND.warning}>Warning notification</Toast>
      <Toast kind={KIND.negative}>Negative notification</Toast>
    </div>
  );
```

-> page is still rendered, but toasts are invisible

**Comment by grrowl** [comment] 2020-06-23 01:06
This may share a root cause with my issue, which has been tricky to track down. It _does_ break on any owner of the ToasterContainer being subject to `cloneElement`. I think in our stack either some graphql or styled-components related pre-render is causing `toasterRef` to be reassigned even though the component assigned to `toasterRef` is never mounted.

I'm hoping the baseweb team will accept a PR moving the `toasterRef` functionality to React context; it'll be a breaking change that will require ToasterContainer to wrap its children but will clean up these issues. In case it helps you debug here's a codesandbox with next and baseweb toast: https://codesandbox.io/s/small-dew-09g9k

**Comment by jgillich** [comment] 2020-06-23 11:42
I think the SSR issue is that the component [returns null unless `state.isMounted` is set](https://github.com/uber/baseweb/blob/master/src/toast/toaster.js#L207), which is set in `componentDidMount` - **after** the first render (SSR only calls render once and never calls componentDidMount). Fix should be to return props.children instead of null.

But while we're at it, we could also move it over to context, if a breaking change is acceptable. @chasestarr

**Comment by chasestarr** [comment] 2020-06-23 18:19
Thanks for the investigation folks. We will investigate the issue

**Closed** 2021-07-22 22:06 UTC
Labels: bug
