### ISSUE TITLE
React Ref Warning when using Baseweb button group with mode "radio"

### ISSUE THREAD

**Issue by briant1234** [uber/baseweb#3404] opened 2020-06-05 21:06 UTC
## Reproduce

To reproduce, I added the button group component to my react app, and passed it the mode prop set to "radio"

## Current Behavior

I've imported baseweb's "ButtonGroup" component, and added it to my react app, using the "Radio" mode. In the console, I get the error that function components cannot be given refs: 
![image](https://user-images.githubusercontent.com/8219120/83922462-53985000-a74e-11ea-8316-1e473e420ac0.png)
It seems like this is related to line 70 in baseweb/src/button-group/button-group.js, as this issue only happens in the radio mode, and not in the checkbox mode.

## Expected Behavior

I would expect no console errors.

## Your Environment

I added this component to my react app, and found this error in the console.

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.81.1  |
| React   |  16.8.0       |
| browser | chrome         |

- [+] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment] 2020-06-09 18:42
Closing due to not being able to reproduce the issue. @briant1234 If you like to continue the conversation, please tag me and include a repro

**Closed by chasestarr** 2020-06-09 18:42 UTC
